name: Docker Image CI

on:
  push:
    branches: ["*"]
    tags: ["*"]

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Source Ref Outputs
      id: source_ref
      run: echo "::set-output name=TAG::${GITHUB_REF#refs/*/}"

    - name: Docker Build
      run: docker build . -f Yabe.Console/Dockerfile -t ghcr.io/shawntoffel/yabe:${{ steps.source_ref.outputs.TAG }}
      working-directory: src

    - name: Docker Push
      run: |
        echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/shawntoffel/yabe:${{ steps.source_ref.outputs.TAG }}
      if: startsWith(github.ref, 'refs/tags/')
